language: java
jdk: oraclejdk7
branches:
  only:
  - master
install: "./gradlew setupCIWorkspace"
script: "./gradlew build"
after_success:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == AlmuraDev/Guide ]] && gradle :uploadArchives"
notifications:
  email: false
env:
  global:
  - TERM=dumb
  - secure: Nq/96KKkz/M7YISYzNNtJLKivztI0uBahp82xKxgLbK4l+K2M7g8iH9gR+9DEISLjOBlsARqo3Lp4D3DV/H1FwvPbECqMOPuIVJ0X4PJOR9s1WDTIcgOT13HdJ67U/1o3cb5UZHwuM12hw9RGeAVKSKSZcJ0HfToIGSkv07xdbc=
  - secure: mcHjq3/+14aHheE7AUIjOI2weAToRAsFrffVV3/4ItHilr6CgD1xLkjTTE44pzrGemSdF0zYYTG0jsi3Mx5jjb73bH+BAGxpNu7MB0V6zdnXEL6SrWAbf2YO7wWi4/1yaSWFreZbZh2d5Ua2k+pcRoYz+NgSkY+EoJ8KY/fe/Wo=
